version: '3'
services:
  getcontact-tg:
    container_name: getcontact-tg
    image: getcontact-tg:${timestamp}
    restart: unless-stopped
    network_mode: host
    environment:
      - TOKEN=${TOKEN}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}

  getcontact-flask:
    container_name: getcontact-flask
    image: getcontact-flask:${timestamp}
    restart: unless-stopped
    network_mode: host
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
